rvm:
  - rbx

before_script:
  - "psql -c 'create database rbxlotto_test;' -U postgres >/dev/null"
  - "cp config/database.yml.example config/database.yml"
script: "bundle exec rake db:drop db:create db:migrate spec cucumber"
